name: Mypy Basic Test

on:
  pull_request:
    branches:
      - master

jobs:
  mypy-basic-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install mypy
        run: |
          python -m pip install --upgrade pip
          pip install mypy==1.10.0

      - name: Debug directory contents
        run: |
          pwd
          echo "Repository contents:"
          ls -la
          echo "Does mypy.ini exist?"
          if [ -f mypy.ini ]; then
            echo "Yes, mypy.ini exists"
            cat mypy.ini
          else
            echo "No, mypy.ini does not exist"
          fi

      - name: Run basic mypy test
        run: |
          # Test with a specific file that's known to exist
          echo "Running mypy on app.py"
          if [ -f mypy.ini ]; then
            mypy --config-file=mypy.ini app.py
          else
            mypy --ignore-missing-imports app.py
          fi